In [3]:
import numpy as np;
import pandas as pd;

In [4]:
np.random.seed(121)
data=pd.DataFrame({"customer_id":np.arange(1,11),
                   "account_balance":np.random.randint(100,200000,10),
                   "credit_score":np.random.randint(500,1000,10),
                   "Transaction_count":np.random.randint(10,100,10),
                   "years_active":np.random.randint(3,10,10),
                   
                   })
data

   customer_id  account_balance  credit_score  Transaction_count  years_active
0            1            11686           936                 98             7
1            2           102969           560                 49             5
2            3            56684           554                 31             9
3            4           182437           503                 51             9
4            5           120600           978                 65             7
5            6           167523           989                 93             9
6            7            94916           552                 23             9
7            8            92306           557                 61             9
8            9            30854           575                 20             7
9           10            19298           995                 13             7

In [64]:
# Q1.1: Create a 4x4 identity matrix
matrix=np.eye(4)
matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [65]:
# Q1.2: Create an array of 8 zeros
array_zeros=np.zeros(8)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
# Q1.3: Create an array of 6 ones
array_ones=np.ones(6)
array_ones

array([1., 1., 1., 1., 1., 1.])

In [43]:
##Q1.4: Create an array with values from 0 to 15
arr=np.arange(0,16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [44]:
#Q1.5: Create an array with 8 evenly spaced values from 0 to 100
arr=np.linspace(0,100,8)
arr

array([  0.        ,  14.28571429,  28.57142857,  42.85714286,
        57.14285714,  71.42857143,  85.71428571, 100.        ])

In [70]:
#Q2.1: What is the shape of the banking_data array?
print(f"shape of banking data:{np.shape(data)}")

shape of banking data:(10, 5)

In [53]:
##Q2.2: What is the data type of the banking_data array?
print(f"type of banking data:{data.dtypes}")

type of banking data:customer_id          int64
account_balance      int32
credit_score         int32
Transaction_count    int32
years_active         int32
dtype: object

In [54]:
##What is the size (total number of elements) of the banking_data array?
print(f"size of data:{np.size(data)}")

size of data:50

In [58]:
#Q2.4: What is the number of dimensions of the banking_data array?
print(f"NUMBER OF DIMENSTION:{data.ndim}")

NUMBER OF DIMENSTION:2

In [5]:
np.random.seed(121)
data1 = np.array([
    np.arange(1,11),                         # Customer_ID
    np.random.randint(1000,10000,10),        # Account_Balance
    np.random.randint(300,900,10),           # Credit_Score
    np.random.randint(10,60,10),             # Transaction_Count
    np.random.randint(1,15,10)               # Years_Active
]).T

print(data1)

[[   1 5565  352   28   14]
 [   2 8432  357   24   13]
 [   3 3113  375   33    9]
 [   4 6812  786   40   13]
 [   5 9531  595   22    1]
 [   6 4583  597   40    8]
 [   7 3814  607   56    8]
 [   8 1948  310   46    2]
 [   9 7198  687   14    4]
 [  10 5073  624   51   13]]

In [85]:
##Q2.5: What is the memory size of the banking_data array in bytes?
print(f"memory size of data:{data1.nbytes}")

memory size of data:400

In [86]:
##Q3.1: Extract the first row of banking_data
print(f"first row of bancking data:{data1[0]}")

first row of bancking data:[   1 5565  352   28   14]

In [87]:
##Q3.2: Extract the last row of banking_data
print(f"last row of bancking data:{data1[-1]}")

last row of bancking data:[  10 5073  624   51   13]

In [88]:
data

   customer_id  account_balance  credit_score  Transaction_count  years_active
0            1              422           546                 67             7
1            2              569           534                 85             5
2            3              364           754                 98             6
3            4              707           936                 49             7
4            5              600           560                 31             5
5            6              165           554                 51             9
6            7              792           503                 65             9
7            8              439           978                 93             7
8            9              611           989                 23             9
9           10              708           552                 61             9

In [90]:
data1

array([[   1, 5565,  352,   28,   14],
       [   2, 8432,  357,   24,   13],
       [   3, 3113,  375,   33,    9],
       [   4, 6812,  786,   40,   13],
       [   5, 9531,  595,   22,    1],
       [   6, 4583,  597,   40,    8],
       [   7, 3814,  607,   56,    8],
       [   8, 1948,  310,   46,    2],
       [   9, 7198,  687,   14,    4],
       [  10, 5073,  624,   51,   13]])

In [91]:
#Q3.3: Extract the Account_Balance column (column index 1)
print(f"account_balance:{data1[:,1]}")

account_balance:[5565 8432 3113 6812 9531 4583 3814 1948 7198 5073]

In [94]:
##Q3.4: Extract the first 4 rows and first 3 columns
print(f"first 4 rows and first 3 columns:{data1[:5,:4]}")

first 4 rows and first 3 columns:[[   1 5565  352   28]
 [   2 8432  357   24]
 [   3 3113  375   33]
 [   4 6812  786   40]
 [   5 9531  595   22]]

In [97]:
#Q3.5: Extract rows 3 to 7 (inclusive)
print(f"Extract rows 3 to 7:{data1[2:7]}")

Extract rows 3 to 7:[[   3 3113  375   33    9]
 [   4 6812  786   40   13]
 [   5 9531  595   22    1]
 [   6 4583  597   40    8]
 [   7 3814  607   56    8]]

In [98]:
#Q4.1: Calculate the sum of all account balances
print(f"sum of account balance:{np.sum(data.account_balance)}")

sum of account balance:5377

In [99]:
#\Q4.2: Calculate the mean account balance
print(f"mean of account_balance:{np.mean(data.account_balance)}")

mean of account_balance:537.7

In [100]:
#Q4.3: Calculate the standard deviation of account balances
print(f"standard deviation of account_balance:{np.std(data.account_balance)}")

standard deviation of account_balance:180.21434460108884

In [101]:
#Q4.4: Calculate the variance of account balances
print(f"variance of account_balance:{np.var(data.account_balance)}")

variance of account_balance:32477.210000000003

In [102]:
#Q4.5: Calculate the median account balance
print(f"median of account_balance:{np.median(data.account_balance)}")

median of account_balance:584.5

In [103]:
#Q5.1: Find the minimum and maximum account balances
print(f"minimum account balance is:{np.min(data.account_balance)}")

minimum account balance is:165

In [104]:
#Q5.2: Find the minimum and maximum credit scores
print(f"minimum credit score is:{np.min(data.credit_score)}")
print(f"maximum credit score is:{np.max(data.credit_score)}")

minimum credit score is:503
maximum credit score is:989

In [106]:
#Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
print(f"25th percentile of account balanceis:{data["account_balance"].quantile([.25,.50,.75])} ")

25th percentile of account balanceis:0.25    426.25
0.50    584.50
0.75    683.00
Name: account_balance, dtype: float64

In [108]:
#Q5.4: Calculate the correlation between account balance and credit score
print(f"correlation between account balance and credit score is :{data["account_balance"].corr(data["credit_score"])} ")

correlation between account balance and credit score is :0.021112488288053288

In [111]:
#Q5.5: Calculate the covariance between account balance and credit score
print(f"coveriance of account balance and creadit score is:{np.cov(data.account_balance,data.credit_score)}")

coveriance of account balance and creadit score is:[[36085.78888889   814.75555556]
 [  814.75555556 41270.48888889]]

In [115]:
##Q6.1: Reshape the banking_data to 5 rows × 10 columns
print(f"reshape of array:{data1.reshape(5,10)}")

reshape of array:[[   1 5565  352   28   14    2 8432  357   24   13]
 [   3 3113  375   33    9    4 6812  786   40   13]
 [   5 9531  595   22    1    6 4583  597   40    8]
 [   7 3814  607   56    8    8 1948  310   46    2]
 [   9 7198  687   14    4   10 5073  624   51   13]]

In [120]:
##Q6.2: Flatten the banking_data to a 1D array
print(f"flatten data1 to 1D:{data1.flatten()}")

flatten data1 to 1D:[   1 5565  352   28   14    2 8432  357   24   13    3 3113  375   33
    9    4 6812  786   40   13    5 9531  595   22    1    6 4583  597
   40    8    7 3814  607   56    8    8 1948  310   46    2    9 7198
  687   14    4   10 5073  624   51   13]

In [ ]:
#Q6.3: Transpose the banking_data
print(f"transpose of data1:{data1.T}")

transpose of data1:[[   1    2    3    4    5    6    7    8    9   10]
 [5565 8432 3113 6812 9531 4583 3814 1948 7198 5073]
 [ 352  357  375  786  595  597  607  310  687  624]
 [  28   24   33   40   22   40   56   46   14   51]
 [  14   13    9   13    1    8    8    2    4   13]]

In [127]:
#Q6.4: Split the banking_data into 2 equal parts vertically
print(f"splited data into 2 vertical equal parts:{np.vsplit(data1,2)}")

splited data into 2 vertical equal parts:[array([[   1, 5565,  352,   28,   14],
       [   2, 8432,  357,   24,   13],
       [   3, 3113,  375,   33,    9],
       [   4, 6812,  786,   40,   13],
       [   5, 9531,  595,   22,    1]]), array([[   6, 4583,  597,   40,    8],
       [   7, 3814,  607,   56,    8],
       [   8, 1948,  310,   46,    2],
       [   9, 7198,  687,   14,    4],
       [  10, 5073,  624,   51,   13]])]

In [138]:
data

   customer_id  account_balance  credit_score  Transaction_count  years_active
0            1              422           546                 67             7
1            2              569           534                 85             5
2            3              364           754                 98             6
3            4              707           936                 49             7
4            5              600           560                 31             5
5            6              165           554                 51             9
6            7              792           503                 65             9
7            8              439           978                 93             7
8            9              611           989                 23             9
9           10              708           552                 61             9

In [140]:
#Q6.5: Split the banking_data into 2 equal parts horizontally
print(f"splited data into  2 horizantal equal parts:{np.hsplit(data1,[2])}")

splited data into  2 horizantal equal parts:[array([[   1, 5565],
       [   2, 8432],
       [   3, 3113],
       [   4, 6812],
       [   5, 9531],
       [   6, 4583],
       [   7, 3814],
       [   8, 1948],
       [   9, 7198],
       [  10, 5073]]), array([[352,  28,  14],
       [357,  24,  13],
       [375,  33,   9],
       [786,  40,  13],
       [595,  22,   1],
       [597,  40,   8],
       [607,  56,   8],
       [310,  46,   2],
       [687,  14,   4],
       [624,  51,  13]])]

In [152]:
#Q7.1: Find customers with account balance greater than $100,000
print(f"customerwith account balance greater than 100000 is :{data.loc[data.account_balance>100000,"customer_id"]}")

customerwith account balance greater than 100000 is :1    2
3    4
4    5
5    6
Name: customer_id, dtype: int64

In [156]:
##Q7.2: Find customers with credit score greater than 800
print(f"customer id greater tan 800 creadit score:{data.loc[data.credit_score>800,"customer_id"]}")

customer id greater tan 800 creadit score:0     1
4     5
5     6
9    10
Name: customer_id, dtype: int64

In [164]:
##Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750
print(f"customers with transaction count greater than 50 AND credit score less than 750:{data.loc[(data.Transaction_count>50) & (data.credit_score<750),"customer_id"]}")

customers with transaction count greater than 50 AND credit score less than 750:3    4
7    8
Name: customer_id, dtype: int64

In [175]:
#Q7.4: Count how many customers have account balance between $10,000 and $100,000
print(f"customers have account balance between $10,000 and $100,000: {data.loc[data.account_balance.between(10000,100000),"customer_id"]}")

customers have account balance between $10,000 and $100,000: 0     1
2     3
6     7
7     8
8     9
9    10
Name: customer_id, dtype: int64

In [179]:
#Q7.5: Find the index of the customer with the highest credit score
print(f"index of high credit score:{np.max(data.credit_score)}")

index of high credit score:995

In [186]:
#Q8.1: Sort the banking_data by account balance (ascending)
print(f"  Sort the banking_data by account balance (ascending):{data.sort_values( by="account_balance" , ascending=True)}")

  Sort the banking_data by account balance (ascending):   customer_id  account_balance  credit_score  Transaction_count  years_active
0            1            11686           936                 98             7
9           10            19298           995                 13             7
8            9            30854           575                 20             7
2            3            56684           554                 31             9
7            8            92306           557                 61             9
6            7            94916           552                 23             9
1            2           102969           560                 49             5
4            5           120600           978                 65             7
5            6           167523           989                 93             9
3            4           182437           503                 51             9

In [188]:
##Q8.2: Sort the banking_data by credit score (descending)
print(f"  Sort the banking_data by account balance (ascending):{data.sort_values( by="account_balance" , ascending=False)}")

  Sort the banking_data by account balance (ascending):   customer_id  account_balance  credit_score  Transaction_count  years_active
3            4           182437           503                 51             9
5            6           167523           989                 93             9
4            5           120600           978                 65             7
1            2           102969           560                 49             5
6            7            94916           552                 23             9
7            8            92306           557                 61             9
2            3            56684           554                 31             9
8            9            30854           575                 20             7
9           10            19298           995                 13             7
0            1            11686           936                 98             7

In [ ]:
##Q8.3: Find the indices that would sort the array by years active
print(f"indices that would sort the array by years active:{np.argsort(data["years_active"])}")

indices that would sort the array by years active:0    1
1    0
2    4
3    8
4    9
5    5
6    3
7    2
8    7
9    6
Name: years_active, dtype: int64

In [ ]:
##Q8.4: Find the customer with the second highest account balance
second_highest_balance=data.sort_values( by="account_balance" , ascending=False).iloc[1]['customer_id']
print(f" customer with the second highest account balance :{second_highest_balance}")

  Sort the banking_data by account balance :6

In [206]:
#Q8.5: Find the customer with the lowest transaction count
print(f"customer with the lowest transaction count:{data.sort_values(by='Transaction_count',ascending=True).iloc[0]['customer_id']}")

customer with the lowest transaction count:10

In [207]:
#Q9.1: Calculate the absolute values of all elements
print(f'absolute values of all elements:{np.abs(data1)}')

absolute values of all elements:[[   1 5565  352   28   14]
 [   2 8432  357   24   13]
 [   3 3113  375   33    9]
 [   4 6812  786   40   13]
 [   5 9531  595   22    1]
 [   6 4583  597   40    8]
 [   7 3814  607   56    8]
 [   8 1948  310   46    2]
 [   9 7198  687   14    4]
 [  10 5073  624   51   13]]

In [208]:
#Q9.2: Calculate the square root of all account balances
print(f'square root of all account balances:{np.sqrt(data.account_balance)}')

square root of all account balances:0    108.101804
1    320.887831
2    238.084019
3    427.126445
4    347.275107
5    409.295737
6    308.084404
7    303.819025
8    175.653067
9    138.917242
Name: account_balance, dtype: float64

In [210]:
#Q9.3: Calculate the square of all credit scores
print(f'square root of all credit scores :{np.sqrt(data.credit_score)}')

square root of all credit scores :0    30.594117
1    23.664319
2    23.537205
3    22.427661
4    31.272992
5    31.448370
6    23.494680
7    23.600847
8    23.979158
9    31.543621
Name: credit_score, dtype: float64

In [211]:
#Q9.4: Calculate the exponential of all transaction counts
print(f"exponential of all transaction counts:{np.exp(data.Transaction_count)}")

exponential of all transaction counts:0    3.637971e+42
1    1.907347e+21
2    2.904885e+13
3    1.409349e+22
4    1.694889e+28
5    2.451246e+40
6    9.744803e+09
7    3.104298e+26
8    4.851652e+08
9    4.424134e+05
Name: Transaction_count, dtype: float64

In [212]:
#Q9.5: Calculate the natural logarithm of all account balances
print(f'natural logarithm of all account balances:{np.log(data.account_balance)}')

natural logarithm of all account balances:0     9.366147
1    11.542183
2    10.945247
3    12.114160
4    11.700235
5    12.028876
6    11.460748
7    11.432864
8    10.337022
9     9.867757
Name: account_balance, dtype: float64

In [213]:
#Q10.1: Calculate the cumulative sum of account balances
print(f"cumulative sum of account balances:{np.cumsum(data.account_balance)}")

cumulative sum of account balances:0     11686
1    114655
2    171339
3    353776
4    474376
5    641899
6    736815
7    829121
8    859975
9    879273
Name: account_balance, dtype: int64

In [214]:
#Q10.2: Calculate the cumulative product of transaction counts
print(f'cumulative product of transaction counts:{np.cumprod(data.Transaction_count)}')

cumulative product of transaction counts:0                   98
1                 4802
2               148862
3              7591962
4            493477530
5          45893410290
6        1055548436670
7       64388454636870
8     1287769092737400
9    16740998205586200
Name: Transaction_count, dtype: int64

In [215]:
#Q10.3: Calculate the difference between consecutive account balances
print(f'difference between consecutive account balances:{data['account_balance'].diff()}')

difference between consecutive account balances:0         NaN
1     91283.0
2    -46285.0
3    125753.0
4    -61837.0
5     46923.0
6    -72607.0
7     -2610.0
8    -61452.0
9    -11556.0
Name: account_balance, dtype: float64

In [216]:
#Q10.4: Calculate the gradient of account balances
print(f'gradient of account balances:{np.gradient(data.account_balance)}')

gradient of account balances:[ 91283.   22499.   39734.   31958.   -7457.  -12842.  -37608.5 -32031.
 -36504.  -11556. ]

In [218]:
#Q10.5: Calculate the histogram of account balances with 5 bins
print(f"histogram of account balances with 5 bins:{np.histogram(data['account_balance'],bins=5)}")

histogram of account balances with 5 bins:(array([3, 1, 3, 1, 2]), array([ 11686. ,  45836.2,  79986.4, 114136.6, 148286.8, 182437. ]))

In [220]:
#Q11.1: Generate 6 random integers between 1 and 1000
np.random.randint(1,1000,6)

array([942, 637,  89, 205, 529, 104], dtype=int32)

In [224]:
#Q11.2: Generate 6 random floats between 0 and 1
np.random.rand(6)

array([0.63254832, 0.54857849, 0.15602992, 0.07164384, 0.27245291,
       0.33596616])

In [225]:
#Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)
np.random.normal(700,100,6)

array([754.93114914, 673.60090763, 860.04268195, 694.82679032,
       728.86956809, 622.08043945])

In [230]:
#Q11.4: Shuffle the banking_data rows randomly
backing_data=data.values
np.random.shuffle(backing_data)
print(backing_data)

[[     2 102969    560     49      5]
 [     9  30854    575     20      7]
 [     4 182437    503     51      9]
 [    10  19298    995     13      7]
 [     7  94916    552     23      9]
 [     5 120600    978     65      7]
 [     3  56684    554     31      9]
 [     8  92306    557     61      9]
 [     1  11686    936     98      7]
 [     6 167523    989     93      9]]

In [233]:
#Q11.5: Set random seed to 123 and generate 4 random numbers
np.random.seed(123)
np.random.randint(10,100,4)

array([76, 27, 93, 67], dtype=int32)

In [235]:
#Q12.1: Calculate the dot product of account balance and credit score columns
print(f"dot product of account balance and credit score columns:{np.dot(data['account_balance'],data['credit_score'])}")

dot product of account balance and credit score columns:616147164

In [240]:
#Q12.2: Calculate the cross product of first two rows
print(f"cross product of first two rows:{np.cross(data.iloc[0,1:4],data.iloc[1,1:4])}")

cross product of first two rows:[    -9016   9518348 -89834824]

In [243]:
#Q12.3: Calculate the norm (magnitude) of the account balance column
print(f"norm (magnitude) of the account balance column:{np.linalg.norm(data['account_balance'])}")

norm (magnitude) of the account balance column:329693.273699965

In [245]:
#Q12.4: Create a 3x3 matrix and calculate its determinant
matrix=np.random.randint(10,100,(3,3))
np.linalg.det(matrix)

np.float64(-62703.00000000001)

In [248]:
#Q12.5: Calculate the inverse of the 3x3 matrix
matrix=np.random.randint(10,100,(3,3))
inverce=np.linalg.inv(matrix)
inverce

array([[-0.02689627, -0.0128434 ,  0.03518977],
       [ 0.02274952, -0.00840869, -0.00835109],
       [-0.00423314,  0.04080516, -0.01426885]])

In [252]:
#Q13.1: Convert all customer IDs to strings
print(f"all customer IDs to strings:{data['customer_id'].astype(str)}")

all customer IDs to strings:0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: customer_id, dtype: object

In [253]:
#Q13.2: Check if any customer ID contains '100'
print(data["customer_id"].astype(str).str.contains("100").any())

False

In [255]:
# Q13.3: Convert all customer IDs to uppercase (if they were strings)
print(f'convert all customer IDs to uppercase:{data['customer_id'].astype(str).str.upper()}')

convert all customer IDs to uppercase:0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: customer_id, dtype: object

In [257]:
#Q13.4: Count the length of each customer ID string
print(f'Count the length of each customer ID string:{data['customer_id'].astype(str).str.len()}')

Count the length of each customer ID string:0    1
1    1
2    1
3    1
4    1
5    1
6    1
7    1
8    1
9    2
Name: customer_id, dtype: int64

In [ ]:
#Q13.5: Replace '100' with 'CUST' in customer IDs

In [259]:
#Q14.1: Convert years active to months
print(f'Convert years active to months:{(data['years_active'])*12}')

Convert years active to months:0     84
1     60
2    108
3    108
4     84
5    108
6    108
7    108
8     84
9     84
Name: years_active, dtype: int32

In [260]:
#Q14.2: Calculate the average years active
print(f" average years active:{np.average(data.years_active)}")

 average years active:7.8

In [264]:
#Q14.3: Find customers who have been active for more than 5 years
print(f"customers who have been active for more than 5 years:{data.years_active>5,['customer_id']}")

customers who have been active for more than 5 years:(0     True
1    False
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
Name: years_active, dtype: bool, ['customer_id'])

In [265]:
#Q14.4: Calculate the total time all customers have been active (in years)
print(f"total time all customers have been active (in years):{data.years_active.sum()}")

total time all customers have been active (in years):78

In [266]:
#Q14.5: Find the customer with the shortest time active
print(f"customer with the shortest time active:{np.min(data.years_active)}")

customer with the shortest time active:5

In [267]:
#Q15.1: Apply a function to calculate 5% interest on all account balances
interset=data['account_balance'].apply(lambda x:x*.005)
print(interset)

0     58.430
1    514.845
2    283.420
3    912.185
4    603.000
5    837.615
6    474.580
7    461.530
8    154.270
9     96.490
Name: account_balance, dtype: float64

In [273]:
#Q15.2: Use np.where to categorize customers by balance ranges
categorize=np.where(data['account_balance']<500,'low',
           np.where(data['account_balance']<=50000,'medium','high'))
categorize

array(['medium', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'medium', 'medium'], dtype='<U6')

In [275]:
#Q15.3: Use np.select to categorize customers by credit score ranges
conditions = [
    data["credit_score"] < 600,
    data["credit_score"] <= 750,
    data["credit_score"] > 750
]

choices = ["Poor", "Average", "Excellent"]

category = np.select(conditions, choices,default="Unknown")

print(category)

['Excellent' 'Poor' 'Poor' 'Poor' 'Excellent' 'Excellent' 'Poor' 'Poor'
 'Poor' 'Excellent']

In [ ]:
#Q15.4: Use np.piecewise to apply different interest rates based on balance

In [277]:
# Q16.1: Concatenate two arrays horizontally using np.hstack()
arr1=np.random.randint(10,100,10)
arr2=np.random.randint(10,100,15)
print(f"Concatenate two arrays horizontally using np.hstack():{np.hstack((arr1,arr2))}")

Concatenate two arrays horizontally using np.hstack():[13 77 21 31 99 13 21 13 16 19 97 24 93 80 22 64 37 48 27 71 84 75 57 26
 15]

In [280]:
# Q16.2: Concatenate two arrays vertically using np.vstack()
arr1=np.random.randint(10,100,10)
arr2=np.random.randint(10,100,10)
print(f"Concatenate two arrays vertically using np.vstack():{np.vstack((arr1,arr2))}")

Concatenate two arrays vertically using np.vstack():[[88 66 97 73 13 27 98 97 79 60]
 [12 28 56 55 67 45 28 56 64 83]]

In [281]:
#Q16.3: Concatenate arrays along a specific axis using np.concatenate()
arr1=np.random.randint(10,100,(2,3))
arr2=np.random.randint(10,100,(2,3))
arr=np.concatenate((arr1,arr2),axis=0)
print(arr1)
print(arr2)
print(arr)

[[91 72 77]
 [21 36 85]]
[[20 13 55]
 [68 69 33]]
[[91 72 77]
 [21 36 85]
 [20 13 55]
 [68 69 33]]

In [ ]:
#Q16.4: Stack arrays depth-wise using np.dstack()

In [282]:
#Q16.5: Create a column stack using np.column_stack()
a=np.array([1,2,3])
b=np.array([4,5,6])
result=np.column_stack((a,b))
result

array([[1, 4],
       [2, 5],
       [3, 6]])

In [284]:
#Q17.1: Split an array into 3 equal parts using np.split()
a=np.array([1,2,3,4,5,6,7,8,9])

result=np.split(a,3)
result

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [287]:
##Q17.2: Split an array at specific indices using np.split()
result=np.split(a,[5,9])
result

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9]), array([], dtype=int64)]

In [292]:
#Q17.3: Split an array horizontally using np.hsplit()
h=np.hsplit(data1,[2])
h

[array([[   1, 5565],
        [   2, 8432],
        [   3, 3113],
        [   4, 6812],
        [   5, 9531],
        [   6, 4583],
        [   7, 3814],
        [   8, 1948],
        [   9, 7198],
        [  10, 5073]]),
 array([[352,  28,  14],
        [357,  24,  13],
        [375,  33,   9],
        [786,  40,  13],
        [595,  22,   1],
        [597,  40,   8],
        [607,  56,   8],
        [310,  46,   2],
        [687,  14,   4],
        [624,  51,  13]])]

In [295]:
#Q17.4: Split an array vertically using np.vsplit()
v=np.vsplit(data1,2)
v

[array([[   1, 5565,  352,   28,   14],
        [   2, 8432,  357,   24,   13],
        [   3, 3113,  375,   33,    9],
        [   4, 6812,  786,   40,   13],
        [   5, 9531,  595,   22,    1]]),
 array([[   6, 4583,  597,   40,    8],
        [   7, 3814,  607,   56,    8],
        [   8, 1948,  310,   46,    2],
        [   9, 7198,  687,   14,    4],
        [  10, 5073,  624,   51,   13]])]

In [298]:
#Q17.5: Split an array into equal chunks using np.array_split()
k=np.array_split(data,3)
k

c:\python\Lib\site-packages\numpy\_core\fromnumeric.py:57: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

[   customer_id  account_balance  credit_score  Transaction_count  years_active
 0            1            11686           936                 98             7
 1            2           102969           560                 49             5
 2            3            56684           554                 31             9
 3            4           182437           503                 51             9,
    customer_id  account_balance  credit_score  Transaction_count  years_active
 4            5           120600           978                 65             7
 5            6           167523           989                 93             9
 6            7            94916           552                 23             9,
    customer_id  account_balance  credit_score  Transaction_count  years_active
 7            8            92306           557                 61             9
 8            9            30854           575                 20             7
 9           10            19298           995                 13             7]

In [301]:
#Q18.1: Repeat each element of an array 3 times using np.repeat()
a=np.array([1,2,3])
result=np.repeat(a,3)
result

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [302]:
#Q18.2: Repeat an entire array 2 times using np.tile()
result=np.tile(a,2)
result

array([1, 2, 3, 1, 2, 3])

In [305]:
#Q18.3: Repeat a 2D array using np.tile()
a=np.array([[1,2],[3,4]])
result=np.tile(a,(2,3))
result

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [306]:
#Q18.4: Create a pattern using np.tile()
b = np.array([0, 1])
pattern = np.tile(b, 5)
print(pattern)

[0 1 0 1 0 1 0 1 0 1]

In [6]:
#Q18.5: Repeat elements with different counts using np.repeat()
a=np.array([1,2,3])
result=np.repeat(a,[2,3,4])
result

array([1, 1, 2, 2, 2, 3, 3, 3, 3])

In [8]:
#Q19.1: Compare two arrays for equality using np.array_equal()
a=np.array([1,2,3])
b=np.array([1,2,3])
print(f"two arrays for equality:{np.array_equal(a,b)}")

two arrays for equality:True

In [ ]:
#Q19.2: Check if arrays are close using np.allclose()

In [ ]:
#Q19.3: Apply logical AND operation between arrays

In [11]:
#Q20.1: Find unique elements in an array using np.unique()
a=np.array([1,2,3])
b=np.array([2,3,4])
combined = np.concatenate((a, b))
print(f"unique elements in an array:{np.unique(combined)}")

unique elements in an array:[1 2 3 4]

In [13]:
#Q20.2: Find the intersection of two arrays using np.intersect1d()
a=np.array([1,2,3])
b=np.array([2,3,4])

print(f"intersection of two arrays:{np.intersect1d(a,b)}")

intersection of two arrays:[2 3]

In [14]:
#20.3: Find the union of two arrays using np.union1d()
a=np.array([1,2,3])
b=np.array([2,3,4])
print(f" union of two arrays:{np.union1d(a,b)}")

 union of two arrays:[1 2 3 4]

In [15]:
#Q20.4: Find elements in first array but not in second using np.setdiff1d()
a=np.array([1,2,3])
b=np.array([2,3,4])
print(f" elements in first array but not in second:{np.setdiff1d(a,b)}")

 elements in first array but not in second:[1]

In [16]:
#Q20.5: Find the symmetric difference between two arrays using np.setxor1d()
a=np.array([1,2,3])
b=np.array([2,3,4])
print(f"the symmetric difference between two arrays:{np.setxor1d(a,b)}")

the symmetric difference between two arrays:[1 4]

In [4]:
print("=" * 60)
print("NUMPY ASSIGNMENT: RETAIL DATA ANALYSIS")
print("=" * 60)
retail_data = np.array([
    [1001, 29.99, 45, 4.2, 15],
    [1002, 49.99, 32, 4.5, 8],
    [1003, 19.99, 78, 3.8, 22],
    [1004, 89.99, 12, 4.7, 5],
    [1005, 15.99, 95, 4.0, 18],
    [1006, 69.99, 28, 4.3, 12],
    [1007, 39.99, 56, 3.9, 20],
    [1008, 79.99, 18, 4.6, 7],
    [1009, 25.99, 67, 4.1, 16],
    [1010, 59.99, 34, 4.4, 10]
])
retail_data

============================================================
NUMPY ASSIGNMENT: RETAIL DATA ANALYSIS
============================================================

array([[1001.  ,   29.99,   45.  ,    4.2 ,   15.  ],
       [1002.  ,   49.99,   32.  ,    4.5 ,    8.  ],
       [1003.  ,   19.99,   78.  ,    3.8 ,   22.  ],
       [1004.  ,   89.99,   12.  ,    4.7 ,    5.  ],
       [1005.  ,   15.99,   95.  ,    4.  ,   18.  ],
       [1006.  ,   69.99,   28.  ,    4.3 ,   12.  ],
       [1007.  ,   39.99,   56.  ,    3.9 ,   20.  ],
       [1008.  ,   79.99,   18.  ,    4.6 ,    7.  ],
       [1009.  ,   25.99,   67.  ,    4.1 ,   16.  ],
       [1010.  ,   59.99,   34.  ,    4.4 ,   10.  ]])

In [5]:
print(f"retail data shape: {retail_data.shape}")

retail data shape: (10, 5)

In [6]:
print(f"retail data type: {retail_data.dtype}")

retail data type: float64

In [7]:
# QUESTION 1: ARRAY CREATION AND MANIPULATION
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [9]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [10]:
print(np.ones(5))

[1. 1. 1. 1. 1.]

In [12]:
print(np.arange(0,10))

[0 1 2 3 4 5 6 7 8 9]

In [13]:
print(np.linspace(0,10,6))

[ 0.  2.  4.  6.  8. 10.]

In [ ]:
# QUESTION 2: ARRAY ATTRIBUTES AND INFORMATION
##Q2.1: What is the shape of the retail_data array?

print(np.shape(retail_data))

(10, 5)

In [22]:
##Q2.2: What is the data type of the retail_data array?
print(f"Data_type:{retail_data.dtype}")

Data_type:float64

In [23]:
##Q2.3: What is the size (total number of elements) of the retail_data array?
print(f"Data_size:{np.size(retail_data)}")

Data_size:50

In [24]:
##Q2.4: What is the number of dimensions of the retail_data array?
print(f"number of dimenstions:{np.ndim(retail_data)}")

number of dimenstions:2

In [25]:
#Q2.5: What is the memory size of the retail_data array in bytes?
print(f"data memory size:{retail_data.nbytes}")

data memory size:400

In [ ]:
# QUESTION 3: INDEXING AND SLICING
#Q3.1: Extract the first row of retail_data